[tool.poetry]
name = "playground"
version = "0.1.0"
description = ""
authors = ["elonp"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "*"
svgwrite = "^1.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
